### ISSUE TITLE
您的框架需要webpack么？

### ISSUE THREAD

**Issue by gongxufan** [yoxjs/yox#37]
支持IE6,对于政务行业码农来说吸引力很大呀。文档和示例再多一点就好了。

**Comment by musicode** [comment]
不需要 webpack，但你也可以加上它




    
    
        
            
                
                    
                        
                    
                    
                        
                            musicode
                            
                            
                                
                                    邮箱：musicode@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2019年07月06日 18:19，潇湘往事 写道： 支持IE6,对于政务行业码农来说吸引力很大呀。文档和示例再多一点就好了。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yoxjs/yox/issues/37?email_source=notifications\u0026email_token=AAU3CD575WERHKTL445UEXTP6BWTLA5CNFSM4H6TDP2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G5U4Y5Q",
"url": "https://github.com/yoxjs/yox/issues/37?email_source=notifications\u0026email_token=AAU3CD575WERHKTL445UEXTP6BWTLA5CNFSM4H6TDP2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G5U4Y5Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by musicode** [comment]
文档这两天在写，有啥需要的例子跟我说

**Comment by hevily** [comment]
webpack 就不大能支持ie6了  加补丁有些也不靠谱

**Comment by musicode** [comment]
我不理解为啥不行，我在文档写了如何打补丁，webpack 难道还会输出其他不兼容的代码？

**Comment by hevily** [comment]
你写的单独引用应该问题不大，直接webpack打包上次我用虚拟机ie试下确实有问题，用ie9调试的7.8调试没有测试出问题 -_- 也有可能是我自己配置问题吧

**Comment by musicode** [comment]
先 close，有问题再反馈

**Comment by musicode** [comment]
我了解了一下，用 ts 开发的话，输出格式选 es3，输出的代码是兼容 IE6 的，babel 我没用过，坑多不敢用
